jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  refresh-expiration-time: 259200000 # 3days
  access-expiration-time: 3600000 # 1hour

cloud:
  aws:
    s3:
      bucket: classic-wave
    credentials:
      access-key: AKIA3FLD453VACPUL7AX
      secret-key: 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
    stack:
      auto: false
    region:
      static: ap-northeast-2

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ClassicWave
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    hikari:
      max-lifetime: 30000
      connection-test-query: SELECT 1
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://classic-wave.cvwu0m44spce.ap-northeast-2.rds.amazonaws.com:3306/classic_wave?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: admin
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  ai:
    stabilityai:
      api-key: sk-0wCRrCCStYZSbj4FRGIk1hOqAWPQyJ6bkiXfLkBAKwfcB0Nv
      image:
        options:
          width: 1024
          height: 512
          style-preset: anime

    openai:
      api-key: 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

server:
  servlet:
    cookie:
      same-site: None
      secure: true

naver:
  cloud:
    api:
      client-secret: ODebzxiUzd
      client-id: BbWzgK5O5u6yuTl0pfPW

# 캐시 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,caches

stabilityai:
  key: sk-0wCRrCCStYZSbj4FRGIk1hOqAWPQyJ6bkiXfLkBAKwfcB0Nv