jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  refresh-expiration-time: 259200000 # 3days
  access-expiration-time: 3600000 # 1hour

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ClassicWave
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classic_wave?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  servlet:
    cookie:
      same-site: None
      secure: true